FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=edsonbzha
ENV N8N_BASIC_AUTH_PASSWORD=tubain@1
ENV WEBHOOK_URL=https://your-project.up.railway.app
ENV N8N_HOST=0.0.0.0
ENV N8N_PORT=3000

EXPOSE 3000